server:
  port: ${SERVER_PORT:8086}
  servlet:
    context-path: ${CONTEXT_PATH:}

spring:
  application:
    name: nexus-portal-backend
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:nexus_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}
      continue-on-error: true
      data-locations:
        - classpath:data.sql
        - classpath:data/01_roles.sql
        - classpath:data/02_users.sql
        - classpath:data/03_products.sql

app:
  jwt:
    secret: ${JWT_SECRET:9a6747f6f64535e3b5acf29c3645e4612482e16136f019f945e7a3ce8b46445b}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
  api:
    prefix: ${API_PREFIX}
    version: ${API_VERSION}
    base-url: ${API_BASE_URL}

springdoc:
  api-docs:
    path: ${SWAGGER_DOCS_PATH}
    enabled: true
  swagger-ui:
    path: ${SWAGGER_UI_PATH}
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

