server:
  port: ${SERVER_PORT:8086}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}

spring:
  application:
    name: nexus-portal-backend
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:nexus_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:9a6747f6f64535e3b5acf29c3645e4612482e16136f019f945e7a3ce8b46445b}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
